2.Matrimonial_App/MatrimonialApp/MatrimonialApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('matrimony.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

2.Matrimonial_App/MatrimonialApp/matrimony/urls.py
from django.urls import path
from . import views

app_name = 'matrimony'

urlpatterns = [
    path('', views.ProfileListView, name='profile_list'),
    path('<int:profile_id>', views.ProfileDetailView, name='profile_detail')
]

2.Matrimonial_App/MatrimonialApp/matrimony/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.conf import settings
fs = FileSystemStorage(location=settings.MEDIA_ROOT)

# Create your models here.


class Profile(models.Model):
    GENDER_COICES = [
        ('M', 'Male'),
        ('F', 'Female'),
    ]
    name = models.CharField(max_length=140)
    profile_pic = models.ImageField(null=True, blank=True)
    age = models.IntegerField(default=0)
    gender = models.CharField(max_length=1, choices=GENDER_COICES)
    occupation = models.CharField(max_length=100, null=True, blank=True)
    place_of_birth = models.CharField(max_length=100, default=False)
    birth_date = models.DateField(null=True)
    is_married = models.BooleanField(default=False)
    email = models.EmailField(max_length=254, unique=True)

    def save(self, *args, **kwargs):
        print(f"Data Updated for {self.name}")
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

2.Matrimonial_App/MatrimonialApp/matrimony/views.py
from django.shortcuts import render
from .models import Profile


def ProfileListView(request):
    profiles = Profile.objects.all()
    return render(request, 'matrimony/profile_list.html', {'profiles': profiles})


def ProfileDetailView(request, profile_id):
    profile = Profile.objects.get(id=profile_id)
    return render(request, 'matrimony/profile_detail.html', {'profile': profile})

2.Matrimonial_App/MatrimonialApp/matrimony/templates/matrimony/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <!-- Load Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>Matrimonial App</title>
</head>
<body>
    {% include 'matrimony/header.html' %}

    <p></p>
    
    <main role="main" class="container">
        {% block content %}{% endblock %}
    </main>

    {% include 'matrimony/footer.html' %}
    
    <!-- Load Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

2.Matrimonial_App/MatrimonialApp/matrimony/templates/matrimony/footer.html
<!-- templates/footer.html -->

<footer class="footer bg-dark mt-5 fixed-bottom">
    <div class="container">
      <span class="text-muted text-center d-block">© 2023 Matrimonial App</span>
    </div>
  </footer>

2.Matrimonial_App/MatrimonialApp/matrimony/templates/matrimony/header.html
<!-- templates/header.html -->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Matrimonial App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'matrimony:profile_list' %}">Home</a>
        </li>
        <!-- Add more links as needed -->
      </ul>
    </div>
  </nav>

2.Matrimonial_App/MatrimonialApp/matrimony/templates/matrimony/profile_detail.html
{% extends 'matrimony/base.html' %}   
{% load static %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <h1 class="center mt-10">Matrimonial App using Django </h1>
    </div>
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="{{ profile.profile_pic.url }}" class="card-img" alt="Profile picture">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ profile.name }}</h5>
                            <p class="card-text"><small class="text-muted">{{ profile.age }} years old</small></p>
                            <p class="card-text">{{ profile.bio }}</p>
                            <p class="card-text">
                                <strong>Occupation:</strong> {{ profile.occupation }}<br>
                                <strong>Date of Birth:</strong> {{ profile.birth_date }}<br>
                                <strong>Marital Status:</strong> {{ profile.is_married|yesno:"Married,Single" }}<br>
                                <strong>Email:</strong> {{ profile.email }}<br>
                            </p>
                            <a href="{% url 'matrimony:profile_list' %}" class="btn btn-primary">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

2.Matrimonial_App/MatrimonialApp/matrimony/templates/matrimony/profile_list.html
{% extends 'matrimony/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <h1 class="center mt-10">Matrimonial App using Django </h1>
    </div>
    <div class="row">
        {% for profile in profiles %}
        <div class="col-md-4">
            <div class="card">
                <img class="card-img-top" src="{{ profile.profile_pic.url }}" alt="Profile picture" width="300" height="400">
                <div class="card-body">
                    <h5 class="card-title">{{ profile.name }}</h5>
                    <a href="{% url 'matrimony:profile_detail' profile.id %}" class="btn btn-primary">View Profile</a>
                </div>
            </div>
            <p></p>
        </div>


        {% endfor %}
    </div>
</div>
{% endblock %}