1. Django Project setup/core/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path("firstApp/", include("firstApp.urls")),
    path("secondApp/", include("secondApp.urls")),
    path("myapp/", include("myapp.urls")),
]

1. Django Project setup/firstApp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
urlpatterns = [
    path('1', home),
]

1. Django Project setup/myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
app_name = "myapp"

urlpatterns = [
    path("index/", index, name='index'),
    path("home/", home, name='home'),
]

1. Django Project setup/secondApp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
urlpatterns = [
    path('1', home2),
]

1. Django Project setup/jaz/models.py
from django.db import models

# Create your models here.

1. Django Project setup/firstApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def home(request):
    return HttpResponse("Hello django home page ")

1. Django Project setup/myapp/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    # read the Database
    # create context variable (dict)
    my_dict = {'pages': ['one', 'two', 'three', 'four'],
               'courses': ['frontend', 'backend']}
    return render(request, 'myapp/index.html', context=my_dict)


def home(request):
    return render(request, 'myapp/home.html')

1. Django Project setup/secondApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def home2(request):
    return HttpResponse("Hello django home 2  page ")

1. Django Project setup/myapp/templates/myapp/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title %}{% endblock  %}
        </title>
    </head>
<body>
{% block content %}
{% endblock  %}
</body>
</html>

1. Django Project setup/myapp/templates/myapp/home.html
{% extends  "myapp/base.html" %}
{% block title %}
    Home
{% endblock  %}

{% block content %}
    
<h1>This is Home page in myapp</h1>
<p>My first paragraph.</p>
<a href="{% url 'myapp:index'%}">Index page</a>

{% endblock  %}

1. Django Project setup/myapp/templates/myapp/index.html
{% extends  "myapp/base.html" %}
{% block title %}
    Index
{% endblock  %}
{% block content %}
    <h1>This is Index page in myapp</h1>
    <p>My first paragraph.</p>
    <h2>List of pages </h2>
    <ul>
      {%for page in pages %}
      <li>{{page}}</li>
      {% endfor %}
    </ul>
    <h2>List of Coureses </h2>
    <ul>
      {%for course  in courses %}
      <li>{{course}}</li>
      {% endfor %}
    </ul>
    <a href="{% url 'myapp:home'%}">Home page</a>
{% endblock  %}